### ISSUE TITLE
🏠 Crear componentes principales: Header, Navbar, HeroSection y Footer

### ISSUE THREAD

**Issue by SanJoseIndoorClub** [SanJoseIndoorClub/WebSite#12]
**Descripción:** 
Desarrollar los componentes básicos del sitio web para construir la estructura principal de la página en `src/components`.

**Tareas:**
1. **Navbar**
   - [ ] Implementar un menú de navegación responsivo en `Navbar.tsx`.

2. **Hero**
   - [ ] Diseñar la sección de bienvenida en `Hero.tsx`.

3. **Footer**
   - [ ] Desarrollar `Footer.tsx` para enlaces de redes sociales, contacto y derechos de autor.

**Objetivo:** 
Construir la estructura visual principal para facilitar la navegación.

**Comment by josephpdf** [comment]
Continuo
