### ISSUE TITLE
🎨 Agregar archivo de estilos

### ISSUE THREAD

**Issue by SanJoseIndoorClub** [SanJoseIndoorClub/WebSite#3]
**Descripción:**
Este issue se enfoca en la creación de un archivo de estilos globales para el proyecto. Este archivo será la base de todos los estilos y ayudará a establecer un diseño coherente en toda la aplicación.

**Tareas:**
- [ ] Crear un archivo `index.css` en la carpeta `src/`.
- [ ] Definir estilos básicos.
- [ ] Importar `index.css` en el archivo principal del proyecto (e.g., `src/main.tsx`).
- [ ] Verificar que los estilos globales se apliquen correctamente al cargar la página.

**Criterios de aceptación:**
- `index.css` debe contener estilos básicos que se reflejen en todas las páginas.
- El archivo debe estar correctamente importado y funcionando en la aplicación.
- Se debe mantener consistencia en los estilos y evitar conflictos con estilos de componentes individuales.

**Notas adicionales:**
El archivo de estilos globales es importante para unificar la apariencia de la aplicación y mantener un diseño consistente a lo largo del desarrollo.

**Comment by josephpdf** [comment]
Voy a continuar con el proyecto
